<?php

if($pin){
    echo'


<!doctype html>
<html class="no-js " lang="en">

<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<title>Meal Ticket</title>
<link rel="stylesheet" href="'.base_url().'assets/plugins/bootstrap/css/bootstrap.min.css">
  <link href="'.base_url().'assets/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body class="pinTicket">
    <div class="pinslip">
    <div class="headerTicket">
    <h2 class="text-center">'.$cafeteria->NAME.'</h2>
    <p>'.$cafeteria->ADDRESS.'</p>
    <p>'.$cafeteria->PHONE.', '.$cafeteria->EMAIL.'</p>
    </div>
        <p>Customer Name : <span>'.$pin->NAME.'</span></p>
        <p>Generated on : <span>'.date("F d, Y", strtotime($pin->DATE_CREATED)).'</span></p>

        <p class="Pin">'.$pin->PIN.'<p>


        <p class="text-center printer">Generated by '.$pin->staff.'</p>
    </div>
</body>



      <script src="'.base_url().'assets/js/jquery.min.js"></script>
        <script src="'.base_url().'assets/js/popper.min.js"></script>

        <script type="text/javascript">

        $(document).ready(function(){
           window.print();
            });
        </script>
    </html>';
}


  
       
   

?>